### ISSUE TITLE
`close_project` or `close_workspace` on Sublime Text 3

### ISSUE THREAD

**Issue by jonasmalacofilho** [mreq/sublime-better-close-window#2]
On the latest dev build (3062), I have to use `close_project` and not `close_workspace`.

Not sure if this is a problem on your code though, it might be a regression on Sublime (assuming that the plugin worked in the previous builds)...

**Comment by jonasmalacofilho** [comment]
Actually, I need both `close_project` and `close_workspace` to clean everything. Weird...

Any ideas? Is there any documentation on the Sublime commands?

**Comment by jonasmalacofilho** [comment]
Build 3062 has quite erratic behaviour for this... Closing the issue for now.

I'll keep testing this on [my fork](https://github.com/jonasmalacofilho/sublime-better-close-window) until the next build is available.

**Comment by randy3k** [comment]
I confirm it with Sublime 3065, Ubuntu.

**Comment by randy3k** [comment]
Actually, to completely mock the same behavior of Mac OSX, I have to modify it as

```
class BetterCloseWindow(sublime_plugin.WindowCommand):
    def run(self):
        # close all files
        self.window.run_command('close_all')
        # check if there are not dirty views
        if any([v.is_dirty() for v in self.window.views()]):
            return
        # close the project
        self.window.run_command('close_project')
        # close the workspace
        self.window.run_command('close_workspace')
        # close the window
        self.window.run_command('close_window')
```
