### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by ghost** [mreq/sublime-better-close-window#4]
Any help on how to use it would be nice. Please provide that too. Multiple window opening is the most annoying feature of the sublime.

**Comment by mreq** [comment]
Provides `better_close_window` command, which does the better closing. Bound to `ctrl+shift+w` by default, see [Default (Linux).sublime-keymap](https://github.com/mreq/sublime-better-close-window/blob/master/Default%20%28Linux%29.sublime-keymap)

**Comment by ghost** [comment]
Sorry if I didn't express myself right. How to use the plugin? Like copy some files to some folders or running anything from the console etc...

Basically how to setup this in to sublime.

**Comment by mreq** [comment]
Oh I see, install it via the [Package control](https://packagecontrol.io/) like any other plugin.
